In [1]:
import keras
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.python.keras as krs
from keras.layers import LSTM, Dropout, Dense, Layer, Conv1D
from keras.models import Sequential
from sklearn.preprocessing import MinMaxScaler
from typing import Union
import itertools

from src import *


2022-11-24 12:04:17.641784: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-24 12:04:17.793939: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-11-24 12:04:17.793959: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-11-24 12:04:17.830204: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-24 12:04:18.643981: W tensorflow/stream_executor/platform/de

In [2]:
res = Cdt1dLayer()(np.array(range(200)).reshape((1, 10, 20)).astype("float"))

2022-11-24 12:04:20.128860: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-11-24 12:04:20.128884: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2022-11-24 12:04:20.128904: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (banjaro): /proc/driver/nvidia/version does not exist
2022-11-24 12:04:20.129151: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
res.shape

(2, 10, 20)

In [4]:
res[0, :, :]

array([[  1.,   3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.,
         33.,  36.,  39.,  42.,  45.,  48.,  51.,  54.,  37.],
       [ 41.,  63.,  66.,  69.,  72.,  75.,  78.,  81.,  84.,  87.,  90.,
         93.,  96.,  99., 102., 105., 108., 111., 114.,  77.],
       [ 81., 123., 126., 129., 132., 135., 138., 141., 144., 147., 150.,
        153., 156., 159., 162., 165., 168., 171., 174., 117.],
       [121., 183., 186., 189., 192., 195., 198., 201., 204., 207., 210.,
        213., 216., 219., 222., 225., 228., 231., 234., 157.],
       [161., 243., 246., 249., 252., 255., 258., 261., 264., 267., 270.,
        273., 276., 279., 282., 285., 288., 291., 294., 197.],
       [201., 303., 306., 309., 312., 315., 318., 321., 324., 327., 330.,
        333., 336., 339., 342., 345., 348., 351., 354., 237.],
       [241., 363., 366., 369., 372., 375., 378., 381., 384., 387., 390.,
        393., 396., 399., 402., 405., 408., 411., 414., 277.],
       [281., 423., 426., 429., 432., 435

In [9]:
res[1, :, :]

array([[  0.5,   1.5,   3. ,   4.5,   6. ,   7.5,   9. ,  10.5,  12. ,
         13.5,  15. ,  16.5,  18. ,  19.5,  21. ,  22.5,  24. ,  25.5,
         27. ,  18.5],
       [ 20.5,  31.5,  33. ,  34.5,  36. ,  37.5,  39. ,  40.5,  42. ,
         43.5,  45. ,  46.5,  48. ,  49.5,  51. ,  52.5,  54. ,  55.5,
         57. ,  38.5],
       [ 40.5,  61.5,  63. ,  64.5,  66. ,  67.5,  69. ,  70.5,  72. ,
         73.5,  75. ,  76.5,  78. ,  79.5,  81. ,  82.5,  84. ,  85.5,
         87. ,  58.5],
       [ 60.5,  91.5,  93. ,  94.5,  96. ,  97.5,  99. , 100.5, 102. ,
        103.5, 105. , 106.5, 108. , 109.5, 111. , 112.5, 114. , 115.5,
        117. ,  78.5],
       [ 80.5, 121.5, 123. , 124.5, 126. , 127.5, 129. , 130.5, 132. ,
        133.5, 135. , 136.5, 138. , 139.5, 141. , 142.5, 144. , 145.5,
        147. ,  98.5],
       [100.5, 151.5, 153. , 154.5, 156. , 157.5, 159. , 160.5, 162. ,
        163.5, 165. , 166.5, 168. , 169.5, 171. , 172.5, 174. , 175.5,
        177. , 118.5],
       [12

In [10]:
res_2 = Cdt1dLayer()(res)

In [12]:
res_2.shape

(4, 10, 20)

In [15]:
res_2[3, :, :]

array([[  1.  ,   2.5 ,   4.5 ,   6.75,   9.  ,  11.25,  13.5 ,  15.75,
         18.  ,  20.25,  22.5 ,  24.75,  27.  ,  29.25,  31.5 ,  33.75,
         36.  ,  38.25,  35.5 ,  22.75],
       [ 26.  ,  42.5 ,  49.5 ,  51.75,  54.  ,  56.25,  58.5 ,  60.75,
         63.  ,  65.25,  67.5 ,  69.75,  72.  ,  74.25,  76.5 ,  78.75,
         81.  ,  83.25,  75.5 ,  47.75],
       [ 51.  ,  82.5 ,  94.5 ,  96.75,  99.  , 101.25, 103.5 , 105.75,
        108.  , 110.25, 112.5 , 114.75, 117.  , 119.25, 121.5 , 123.75,
        126.  , 128.25, 115.5 ,  72.75],
       [ 76.  , 122.5 , 139.5 , 141.75, 144.  , 146.25, 148.5 , 150.75,
        153.  , 155.25, 157.5 , 159.75, 162.  , 164.25, 166.5 , 168.75,
        171.  , 173.25, 155.5 ,  97.75],
       [101.  , 162.5 , 184.5 , 186.75, 189.  , 191.25, 193.5 , 195.75,
        198.  , 200.25, 202.5 , 204.75, 207.  , 209.25, 211.5 , 213.75,
        216.  , 218.25, 195.5 , 122.75],
       [126.  , 202.5 , 229.5 , 231.75, 234.  , 236.25, 238.5 , 240.75,
   

In [13]:
input_shape = (10,20,)

model = keras.Sequential()
#model.add(tf.keras.Input(shape=(10, None,)))

model.add(Cdt1dLayer(input_shape=input_shape))
model.add(tf.keras.layers.MaxPooling1D(pool_size=3, strides=3, padding='same'))

for i in range(6):
    model.add(Cdt1dLayer())
    model.add(tf.keras.layers.MaxPooling1D(pool_size=3, strides=3, padding='same'))

model.add(tf.keras.layers.Dense(12))
model.add(tf.keras.layers.Dense(7))
model.add(tf.keras.layers.Dense(3, activation="softmax"))

model.build(input_shape)

ValueError: Exception encountered when calling layer "module_wrapper_28" "                 f"(type ModuleWrapper).

in user code:

    File "/home/bartko/Repozytoria/inzynierka/src/CDT_1D_CNN/cdt_1d_layer.py", line 57, in call  *
        inputs_flat = inputs_flat_with_pad(inputs)
    File "/home/bartko/Repozytoria/inzynierka/src/CDT_1D_CNN/cdt_1d_layer.py", line 87, in inputs_flat_with_pad  *
        dim_batches, dim_y, dim_x = inputs.shape

    ValueError: not enough values to unpack (expected 3, got 2)


Call arguments received by layer "module_wrapper_28" "                 f"(type ModuleWrapper):
  • args=('tf.Tensor(shape=(10, 20), dtype=float32)',)
  • kwargs={'training': 'None'}

In [12]:
model.summary()

ValueError: This model has not yet been built. Build the model first by calling `build()` or by calling the model on a batch of data.

In [6]:
inputs_flat = inputs_flat_with_pad(res)
filt = filter_combine([1, 1, 1], [0.5, 0.5, 0.5], in_channels=inputs_flat.shape[2])


In [7]:
inputs_flat.shape

(2, 24, 1)

In [8]:
inputs_flat[0, :, :]

array([[ 1.],
       [ 3.],
       [ 6.],
       [ 9.],
       [ 7.],
       [ 0.],
       [11.],
       [18.],
       [21.],
       [24.],
       [17.],
       [ 0.],
       [21.],
       [33.],
       [36.],
       [39.],
       [27.],
       [ 0.],
       [31.],
       [48.],
       [51.],
       [54.],
       [37.],
       [ 0.]])

In [10]:
inputs_flat[1, :, :]

array([[ 0.5],
       [ 1.5],
       [ 3. ],
       [ 4.5],
       [ 3.5],
       [ 0. ],
       [ 5.5],
       [ 9. ],
       [10.5],
       [12. ],
       [ 8.5],
       [ 0. ],
       [10.5],
       [16.5],
       [18. ],
       [19.5],
       [13.5],
       [ 0. ],
       [15.5],
       [24. ],
       [25.5],
       [27. ],
       [18.5],
       [ 0. ]])

In [13]:
filt.shape

(3, 1, 2)

In [16]:
filt[:, :, 0]

array([[1.],
       [1.],
       [1.]])

In [ ]:
res_2 = tf.nn.convolution(input=inputs_flat, filters=filt, padding="SAME").numpy()

In [90]:
res_2_0 = np.zeros((1, res_2.shape[1], res_2.shape[0] + res_2.shape[2]))

indexes = itertools.product(range(res_2.shape[0]), range(res_2.shape[2]))
for i, _jk in enumerate(indexes):
    j, k = _jk
    res_2_0[0, :, i] = res_2[j, :, k]
res_2 = res_2_0
res_2 = res_2.reshape((4, -1, 4))[:,:-1,:]


In [91]:
res_2.shape

(4, 5, 4)

In [96]:
res_2[:, :, 0]

array([[  4.,  10.,  18.,  22.,  16.],
       [ 29.,  50.,  63.,  62.,  41.],
       [ 54.,  90., 108., 102.,  66.],
       [ 79., 130., 153., 142.,  91.]])

In [39]:
res_2.reshape(4, -1, 1)[0, :, 0]

array([ 4. ,  2. , 10. ,  5. , 18. ,  9. , 22. , 11. , 16. ,  8. , 18. ,
        9. , 29. , 14.5, 50. , 25. , 63. , 31.5, 62. , 31. , 41. , 20.5,
       38. , 19. ])

In [45]:
res[:, :, 0]

array([[ 1.,  3.,  6.,  9.,  7.],
       [11., 18., 21., 24., 17.],
       [21., 33., 36., 39., 27.],
       [31., 48., 51., 54., 37.]])

In [25]:
res[:, :, 1]

array([[ 0.5,  1.5,  3. ,  4.5,  3.5],
       [ 5.5,  9. , 10.5, 12. ,  8.5],
       [10.5, 16.5, 18. , 19.5, 13.5],
       [15.5, 24. , 25.5, 27. , 18.5]])

In [30]:
print(inputs_flat.shape)
print(filt.shape)
print(res_2.shape)


(2, 24, 1)
(3, 1, 2)
(2, 24, 2)


In [3]:
a = np.array([[[1, 2, 3], [4, 5, 6]]])

In [4]:
a[0, :, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.reshape((2, 3, 1))[:, :, 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a.shape

(1, 2, 3)

In [ ]:
res_0 = np.zeros((res.shape[0], res.shape[1]+4, res.shape[2]))

In [18]:
res_mp = tf.keras.layers.MaxPooling1D(pool_size=3, strides=3, padding='same')(res[:, :, :]).numpy()


In [19]:
res_mp.shape

(10, 7, 2)

In [21]:
res[:, :, 1]

array([[  0.5,   1.5,   3. ,   4.5,   6. ,   7.5,   9. ,  10.5,  12. ,
         13.5,  15. ,  16.5,  18. ,  19.5,  21. ,  22.5,  24. ,  25.5,
         27. ,  18.5],
       [ 20.5,  31.5,  33. ,  34.5,  36. ,  37.5,  39. ,  40.5,  42. ,
         43.5,  45. ,  46.5,  48. ,  49.5,  51. ,  52.5,  54. ,  55.5,
         57. ,  38.5],
       [ 40.5,  61.5,  63. ,  64.5,  66. ,  67.5,  69. ,  70.5,  72. ,
         73.5,  75. ,  76.5,  78. ,  79.5,  81. ,  82.5,  84. ,  85.5,
         87. ,  58.5],
       [ 60.5,  91.5,  93. ,  94.5,  96. ,  97.5,  99. , 100.5, 102. ,
        103.5, 105. , 106.5, 108. , 109.5, 111. , 112.5, 114. , 115.5,
        117. ,  78.5],
       [ 80.5, 121.5, 123. , 124.5, 126. , 127.5, 129. , 130.5, 132. ,
        133.5, 135. , 136.5, 138. , 139.5, 141. , 142.5, 144. , 145.5,
        147. ,  98.5],
       [100.5, 151.5, 153. , 154.5, 156. , 157.5, 159. , 160.5, 162. ,
        163.5, 165. , 166.5, 168. , 169.5, 171. , 172.5, 174. , 175.5,
        177. , 118.5],
       [12

In [22]:
res_mp[:, :, 1]

array([[  3. ,   7.5,  12. ,  16.5,  21. ,  25.5,  27. ],
       [ 33. ,  37.5,  42. ,  46.5,  51. ,  55.5,  57. ],
       [ 63. ,  67.5,  72. ,  76.5,  81. ,  85.5,  87. ],
       [ 93. ,  97.5, 102. , 106.5, 111. , 115.5, 117. ],
       [123. , 127.5, 132. , 136.5, 141. , 145.5, 147. ],
       [153. , 157.5, 162. , 166.5, 171. , 175.5, 177. ],
       [183. , 187.5, 192. , 196.5, 201. , 205.5, 207. ],
       [213. , 217.5, 222. , 226.5, 231. , 235.5, 237. ],
       [243. , 247.5, 252. , 256.5, 261. , 265.5, 267. ],
       [273. , 277.5, 282. , 286.5, 291. , 295.5, 297. ]], dtype=float32)